export default [
  {
    id: 1,
    title: "Title 1",
    description: "Description 1",
    imgL: "L/01.jpg",
    imgXS: "XS/01.png",
    start: 1500,
    end: 1503,
    categogy: 1,
  },
  {
    id: 2,
    title: "Title 2",
    description: "Description 2",
    imgL: "L/02.jpg",
    imgXS: "XS/02.png",
    start: 1503,
    end: 1505,
    categogy: 2,
  },
  {
    id: 3,
    title: "Title 3",
    description: "Description 3",
    imgL: "L/03.jpg",
    imgXS: "XS/03.png",
    start: 1505,
    end: 1505,
    categogy: 3,
  },
  {
    id: 4,
    title: "Title 4",
    description: "Description 4",
    imgL: "L/04.jpg",
    imgXS: "XS/04.png",
    start: 1506,
    end: 1510,
    categogy: 4,
  },
  {
    id: 5,
    title: "Title 5",
    description: "Description 5",
    imgL: "L/05.jpg",
    imgXS: "XS/05.png",
    start: 1507,
    end: 1507,
    categogy: 1,
  },
  {
    id: 6,
    title: "Title 6",
    description: "Description 6",
    imgL: "L/06.jpg",
    imgXS: "XS/06.png",
    start: 1510,
    end: 1515,
    categogy: 2,
  },
  {
    id: 7,
    title: "Title 7",
    description: "Description 7",
    imgL: "L/07.jpg",
    imgXS: "XS/07.png",
    start: 1545,
    end: 1545,
    categogy: 3,
  },
  {
    id: 8,
    title: "Title 8",
    description: "Description 8",
    imgL: "L/08.jpg",
    imgXS: "XS/08.png",
    start: 1545,
    end: 1560,
    categogy: 4,
  },
  {
    id: 9,
    title: "Title 9",
    description: "Description 9",
    imgL: "L/09.jpg",
    imgXS: "XS/09.png",
    start: 1555,
    end: 1570,
    categogy: 1,
  },
  {
    id: 10,
    title: "Title 10",
    description: "Description 10",
    imgL: "L/10.jpg",
    imgXS: "XS/10.png",
    start: 1565,
    end: 1570,
    categogy: 2,
  },
  {
    id: 11,
    title: "Title 11",
    description: "Description 11",
    imgL: "L/11.jpg",
    imgXS: "XS/11.png",
    start: 1580,
    end: 1590,
    categogy: 3,
  },
  {
    id: 12,
    title: "Title 12",
    description: "Description 12",
    imgL: "L/12.jpg",
    imgXS: "XS/12.png",
    start: 1590,
    end: 1600,
    categogy: 4,
  },
  {
    id: 13,
    title: "Title 13",
    description: "Description 13",
    imgL: "L/13.jpg",
    imgXS: "XS/13.png",
    start: 1600,
    end: 1629,
    categogy: 1,
  },
  {
    id: 14,
    title: "Title 14",
    description: "Description 14",
    imgL: "L/14.jpg",
    imgXS: "XS/14.png",
    start: 1620,
    end: 1625,
    categogy: 2,
  },
  {
    id: 15,
    title: "Title 15",
    description: "Description 15",
    imgL: "L/15.jpg",
    imgXS: "XS/15.png",
    start: 1630,
    end: 1630,
    categogy: 3,
  },
];
